package com.example.mobilab_test_assignment.model

/**
 * ItemModel is the model for the items in this application
 * Every item consists of:
 * Auto generated by the database Int id
 * listId shows which list this item belongs to
 * value shows what is the String title or content what was inserted when creating this item
 * checkedState show whether the checkbox on this item is checked (true) or unchecked (false)
 */
data class ItemModel (val id: Int, val listId: Int, val value: String, val checkedState: Boolean)